data:
  DHI_folder: Data/Dataset/VDI
  input_width: 512
  input_height: 512
model:
  batch_size: 8
  num_epochs: 5
  learning_rate: 0.0001
  train_ratio: 0.8
  val_ratio: 0.1
  test_ratio: 0.1
  Pretrain_PATH: model.pth
  num_coefficients: 3
  # dataset_name: vision-paper/DHI
  resolution: 512
  result_path: result
  model_path: models/ddt
  base_model_path: 
  image_encoder_path:
  ip_ckpt:
  canny_model_path:
  pose_model_path:
  segment_model_path:
