data:
  DHI_folder: Data/Dataset/DHI
  input_width: 512
  input_height: 512
model:
  batch_size: 1
  num_epochs: 5
  learning_rate: 0.0001
  train_ratio: 0.8
  val_ratio: 0.1
  test_ratio: 0.1
  Pretrain_PATH: model.pth
  num_coefficients: 4
  dataset_name: NegarMov/DHI
  resolution: 512
  result_path: result
  model_path: models/ddt
  base_model_path: "C:/Users/tabatabaei/vision/models/realisticVisionV60B1_v51VAE-inpainting.safetensors"
  image_encoder_path: "models/image_encoder/"
  ip_ckpt: "models/ip-adapter_sd15.bin"
  canny_model_path: "lllyasviel/sd-controlnet-canny"
  pose_model_path: "C:/Users/tabatabaei/vision/diffusers/examples/controlnet/models/cn_pose"
  segment_model_path: "C:/Users/tabatabaei/vision/diffusers/examples/controlnet/models/controlnet-seg-finetuned"
